### ISSUE TITLE
Fix service call for setting a config value

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/backlog#12] opened 2023-07-13 13:56 UTC
![Image](https://github.com/zwave-js/certification-backlog/assets/6389780/8436f6e8-5eb2-4dba-bbd5-b4d85a11bed4)

**Comment by AlCalzone** [comment] 2023-11-20 10:58
> Also, resetting all config parameters (and optionally, individual ones) to default must be supported.

This is not supported yet

**Comment by AlCalzone** [comment] 2023-11-20 11:00
-

**Comment by AlCalzone** [comment] 2023-11-20 11:02
The service call is broken too:


![Image](https://github.com/zwave-js/certification-backlog/assets/17641229/575feb1a-8aa5-40e3-b003-be210c2c27a7)

**Comment by AlCalzone** [comment] 2023-11-20 11:03
Refreshing such a config parameter seems also not supported, this is not a requirement though.

**Comment by marcelveldt** [comment] 2023-11-23 10:19
This task has been split up into multiple smaller ones. Left is fixing the set config value service call.

**Comment by raman325** [comment] 2023-11-23 15:07
@AlCalzone according to the typing here: https://github.com/zwave-js/node-zwave-js/blob/master/packages/cc/src/cc/ConfigurationCC.ts#L107

`valueFormat` is required alongside `valueSize`. Is that correct? If so then this behavior is correct and should be expected. If not, then should we update the type? This will need to be fixed in the server and lib as well

**Comment by AlCalzone** [comment] 2024-01-06 18:02
Hmm, you're right. I could have sworn it defaults to signed. In this case it's just the error message that's terrible.

**Comment by raman325** [comment] 2024-01-06 18:11
Yeah unfortunately that comes from the validator we use. I'll look into customizing the message

**Comment by marcelveldt** [comment] 2024-07-04 08:27
This is a candidate for the expert UI

**Comment by AlCalzone** [comment] 2024-09-02 21:42
- [ ] Figure out if we can move the service call for setting custom config parameter into the expert UI
- [ ] Make it impossible to provide incomplete/invalid combinations of options. Allowed:
	1. parameter + value
	2. parameter + bitmask + value
	3. parameter + value + value size + value format
- [ ] Figure out if points 1 and 2 should even be supported. They should have corresponding values that can just be set directly.

**Comment by MartinHjelmare** [comment] 2024-09-03 07:44
I think we should first fix the service call. Then we can do the rest. We can't remove the service call, if we even want that, without a long deprecation time anyway.

The service to be fixed is named `zwave_js.set_config_parameter`.

**Comment by MindFreeze** [comment] 2024-10-29 14:02
The fixed service will merged with https://github.com/home-assistant/core/pull/129332

**Comment by MindFreeze** [comment] 2024-11-11 06:59
Maybe we can close this issue. The service validation has been removed. A new UI for custom params is added in #31 but in the node config page, not the expert UI.
Is there anything else to do here? Maybe tweak the validation?

**Comment by AlCalzone** [comment] 2024-11-12 11:31
I'll double check that it works as intended, then close 👍🏻

**Closed as completed** 2024-12-04 12:57 UTC
Labels: new feature, frontend, zwave-certification, expert-ui
